### ISSUE TITLE
Visual design for new elements to be integrated in the page

### ISSUE THREAD

**Issue by pamichel** [calipho-sib/nextprot-snorql#1]
Elements to add:

1/ A link to the RDF Help page
- clicking the link should switch to the RDF HELP page
- it should be possible to switch back easily from the HHELP pgage to the SNORQL search page

2/ A link allowing the user to send an e-mail to the support team
- the user should understand that the support team will help him to write sparql for him
- answer specific questions about our RDF model
- troubleshooting
- suggestion ? ...

3/ A table of statistics about the RDF data
- number of entries, isoforms, ... (to be defined)

**Comment by evaletolab** [comment]
tu penses qu'on peut fermer la tâche? On pourrait manger à midi pour en parler?

**Comment by ddtxra** [comment]
+1 for the lunch

**Comment by evaletolab** [comment]
:+1:
